version: "3.3"
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  servicemysql:
    build: ./service-mysql
    ports:
      - "6000:6000"

  serviceimportdata:
    build: ./service-import-data
    ports:
      - "5050:5050"

  serviceconsult:
    build: ./service-consult
    ports:
      - "5000:5000"

      
volumes:
  mysql-data:
    driver: local
